### ISSUE TITLE
Flipped arguments on Maybe.withDefault in Brave New W..Holy Cow chapter

### ISSUE THREAD

**Issue by wking-io** [mordrax/elm-at-phd-book#1]
Hey! 

Loving the overview of you breaking your experience of using Elm professionally! Just wanted to help point out the argument swap in the Brave New W...Holy Cow chapter: http://package.elm-lang.org/packages/elm-lang/core/latest/Maybe#withDefault

Thought of making a PR but figured it would be super easy for you to update. Thank you for writing this! :)

**Comment by mordrax** [comment]
Well spotted, hope you found it useful/insightful! Fixed.
